### ISSUE TITLE
Error when maskingCharacters is negative

### ISSUE THREAD

**Issue by kigoldman** [Sumukha1496/maskdata#12]
https://github.com/Sumukha1496/maskdata/blob/master/index.js#L54

If `maskingCharacters` is negative, could it be set to `0`?

```
  const maskingCharacters = maskPasswordLength - options.unmaskedStartCharacters - options.unmaskedEndCharacters;
    maskedPassword = password.substr(0, options.unmaskedStartCharacters);
    maskedPassword += `${options.maskWith}`.repeat(maskingCharacters)
```

**Comment by Sumukha1496** [comment]
@kigoldman, Can you please give me the scenario when it is happening. 
May be some example configs will help

**Comment by kigoldman** [comment]
Sure. I was trying out different scenarios, and received this error:
```
RangeError: Invalid count value
    at String.repeat (<anonymous>)
    at Function.maskPassword (~/node_modules/maskdata/index.js:56:45)

```

And this was the call I was making:
```
 return MaskData.maskPassword(value_to_mask, {
   maskWith: '-',
   maxMaskedCharacters: 3,
   unmaskedStartCharacters: 0,
   unmaskedEndCharacters: 4,
 });

```

**Comment by Sumukha1496** [comment]
Got it. Working on it.
But if you see the use case, you want the last 4 characters to be kept as it is and at the same time, you max 3 characters in the output. 
Technically it is an issue but usecase-wise, I think it is a strange usecase. 
You can expect the fix by today EOD. 

If maskingCharacters is negative, could it be set to 0? --> No. If the maskingCharacters is negative, I will start with the unmaskedStartCharacters and then unmaskedEndCharacters by adjusting it to maskingCharacters.

for example, 

return MaskData.maskPassword('123456789', {
   maskWith: '-',
   maxMaskedCharacters: 3,
   unmaskedStartCharacters: 1,
   unmaskedEndCharacters: 4,
 });

Since you want only 3 characters in the output,

unmaskedStartCharacters = 1  ==> output = "1"
unmaskedEndCharacters = 4  But 1 character is by unmaskedStartCharacters and we are left with (maxMaskedCharacters - unmaskedStartCharacters. i.e, 3-1 = 2 ==> unmaskedStartCharacters = 2) ==> output = "189"

So final output will be "189"

**Comment by Sumukha1496** [comment]
Fixed it. Can you check version 1.1.4? :

**Comment by Sumukha1496** [comment]
If it is working fine, I will close the ticket. Let me know. 
Also, Thank you for raising the issue.

**Comment by Sumukha1496** [comment]
@kigoldman , Did you get a chance to verify the fix in the new version?

**Comment by Sumukha1496** [comment]
.

**Comment by kigoldman** [comment]
Hey. Thanks for taking care of this. I had come across this error when passing variables to the method. I had wrapped a method around this call, and was using my wrapper to mask a bunch of different elements.

**Comment by Sumukha1496** [comment]
No problem. Please raise issues if there are any or if you want some new feature
