### ISSUE TITLE
is it possible to unmask ?

### ISSUE THREAD

**Issue by Sinbad-93** [Sumukha1496/maskdata#14]
Hello, 
First, thk u for u're work, it's awesome. :)
i'm a newbie dev, so i hope it's not a problem of bad read, but,
 i haven't see how to unmask data ? 
So if we can't, we never can use again the data ?
thk u for attention,
bests regards

**Comment by Sumukha1496** [comment]
Hi @Sinbad-93, 
Thanks for raising the issue. 
Masking doesn't use any algorithms. so, unmasking is not possible. Maybe you can take a look into **encryption and decryption**. 

One other way is, keep the actual data in hand. While masking, create a copy of the data and use it wherever it is needed so that you can have both masked and actual data.
